package com.example.reportviolation.domain.service

import com.example.reportviolation.data.model.Country

class CountryService {
    
    companion object {
        private val countries = listOf(
            Country("Afghanistan", "AF", "93", phoneNumberLength = 9),
            Country("Albania", "AL", "355", phoneNumberLength = 9),
            Country("Algeria", "DZ", "213", phoneNumberLength = 9),
            Country("Andorra", "AD", "376", phoneNumberLength = 6),
            Country("Angola", "AO", "244", phoneNumberLength = 9),
            Country("Argentina", "AR", "54", phoneNumberLength = 10),
            Country("Armenia", "AM", "374", phoneNumberLength = 8),
            Country("Australia", "AU", "61", phoneNumberLength = 9),
            Country("Austria", "AT", "43", phoneNumberLength = 10),
            Country("Azerbaijan", "AZ", "994", phoneNumberLength = 9),
            Country("Bahrain", "BH", "973", phoneNumberLength = 8),
            Country("Bangladesh", "BD", "880", phoneNumberLength = 10),
            Country("Belarus", "BY", "375", phoneNumberLength = 9),
            Country("Belgium", "BE", "32", phoneNumberLength = 9),
            Country("Belize", "BZ", "501", phoneNumberLength = 7),
            Country("Benin", "BJ", "229", phoneNumberLength = 8),
            Country("Bhutan", "BT", "975", phoneNumberLength = 8),
            Country("Bolivia", "BO", "591", phoneNumberLength = 8),
            Country("Bosnia and Herzegovina", "BA", "387", phoneNumberLength = 8),
            Country("Botswana", "BW", "267", phoneNumberLength = 8),
            Country("Brazil", "BR", "55", phoneNumberLength = 11),
            Country("Brunei", "BN", "673", phoneNumberLength = 7),
            Country("Bulgaria", "BG", "359", phoneNumberLength = 9),
            Country("Burkina Faso", "BF", "226", phoneNumberLength = 8),
            Country("Burundi", "BI", "257", phoneNumberLength = 8),
            Country("Cambodia", "KH", "855", phoneNumberLength = 9),
            Country("Cameroon", "CM", "237", phoneNumberLength = 8),
            Country("Canada", "CA", "1", phoneNumberLength = 10),
            Country("Cape Verde", "CV", "238", phoneNumberLength = 7),
            Country("Central African Republic", "CF", "236", phoneNumberLength = 8),
            Country("Chad", "TD", "235", phoneNumberLength = 8),
            Country("Chile", "CL", "56", phoneNumberLength = 9),
            Country("China", "CN", "86", phoneNumberLength = 11),
            Country("Colombia", "CO", "57", phoneNumberLength = 10),
            Country("Comoros", "KM", "269", phoneNumberLength = 7),
            Country("Congo", "CG", "242", phoneNumberLength = 9),
            Country("Costa Rica", "CR", "506", phoneNumberLength = 8),
            Country("Croatia", "HR", "385", phoneNumberLength = 9),
            Country("Cuba", "CU", "53", phoneNumberLength = 8),
            Country("Cyprus", "CY", "357", phoneNumberLength = 8),
            Country("Czech Republic", "CZ", "420", phoneNumberLength = 9),
            Country("Denmark", "DK", "45", phoneNumberLength = 8),
            Country("Djibouti", "DJ", "253", phoneNumberLength = 8),
            Country("Dominican Republic", "DO", "1", phoneNumberLength = 10),
            Country("Ecuador", "EC", "593", phoneNumberLength = 9),
            Country("Egypt", "EG", "20", phoneNumberLength = 10),
            Country("El Salvador", "SV", "503", phoneNumberLength = 8),
            Country("Equatorial Guinea", "GQ", "240", phoneNumberLength = 9),
            Country("Eritrea", "ER", "291", phoneNumberLength = 7),
            Country("Estonia", "EE", "372", phoneNumberLength = 8),
            Country("Eswatini", "SZ", "268", phoneNumberLength = 8),
            Country("Ethiopia", "ET", "251", phoneNumberLength = 9),
            Country("Fiji", "FJ", "679", phoneNumberLength = 7),
            Country("Finland", "FI", "358", phoneNumberLength = 9),
            Country("France", "FR", "33", phoneNumberLength = 9),
            Country("Gabon", "GA", "241", phoneNumberLength = 8),
            Country("Gambia", "GM", "220", phoneNumberLength = 7),
            Country("Georgia", "GE", "995", phoneNumberLength = 9),
            Country("Germany", "DE", "49", phoneNumberLength = 10),
            Country("Ghana", "GH", "233", phoneNumberLength = 9),
            Country("Greece", "GR", "30", phoneNumberLength = 10),
            Country("Guatemala", "GT", "502", phoneNumberLength = 8),
            Country("Guinea", "GN", "224", phoneNumberLength = 9),
            Country("Guinea-Bissau", "GW", "245", phoneNumberLength = 7),
            Country("Guyana", "GY", "592", phoneNumberLength = 7),
            Country("Haiti", "HT", "509", phoneNumberLength = 8),
            Country("Honduras", "HN", "504", phoneNumberLength = 8),
            Country("Hong Kong", "HK", "852", phoneNumberLength = 8),
            Country("Hungary", "HU", "36", phoneNumberLength = 9),
            Country("Iceland", "IS", "354", phoneNumberLength = 7),
            Country("India", "IN", "91", phoneNumberLength = 10),
            Country("Indonesia", "ID", "62", phoneNumberLength = 9),
            Country("Iran", "IR", "98", phoneNumberLength = 10),
            Country("Iraq", "IQ", "964", phoneNumberLength = 10),
            Country("Ireland", "IE", "353", phoneNumberLength = 9),
            Country("Israel", "IL", "972", phoneNumberLength = 9),
            Country("Italy", "IT", "39", phoneNumberLength = 10),
            Country("Ivory Coast", "CI", "225", phoneNumberLength = 10),
            Country("Jamaica", "JM", "1", phoneNumberLength = 10),
            Country("Japan", "JP", "81", phoneNumberLength = 10),
            Country("Jordan", "JO", "962", phoneNumberLength = 9),
            Country("Kazakhstan", "KZ", "7", phoneNumberLength = 10),
            Country("Kenya", "KE", "254", phoneNumberLength = 9),
            Country("Kuwait", "KW", "965", phoneNumberLength = 8),
            Country("Kyrgyzstan", "KG", "996", phoneNumberLength = 9),
            Country("Laos", "LA", "856", phoneNumberLength = 10),
            Country("Latvia", "LV", "371", phoneNumberLength = 8),
            Country("Lebanon", "LB", "961", phoneNumberLength = 8),
            Country("Lesotho", "LS", "266", phoneNumberLength = 8),
            Country("Liberia", "LR", "231", phoneNumberLength = 8),
            Country("Libya", "LY", "218", phoneNumberLength = 9),
            Country("Lithuania", "LT", "370", phoneNumberLength = 8),
            Country("Luxembourg", "LU", "352", phoneNumberLength = 9),
            Country("Macau", "MO", "853", phoneNumberLength = 8),
            Country("Madagascar", "MG", "261", phoneNumberLength = 9),
            Country("Malawi", "MW", "265", phoneNumberLength = 9),
            Country("Malaysia", "MY", "60", phoneNumberLength = 9),
            Country("Maldives", "MV", "960", phoneNumberLength = 7),
            Country("Mali", "ML", "223", phoneNumberLength = 8),
            Country("Malta", "MT", "356", phoneNumberLength = 8),
            Country("Mauritania", "MR", "222", phoneNumberLength = 8),
            Country("Mauritius", "MU", "230", phoneNumberLength = 8),
            Country("Mexico", "MX", "52", phoneNumberLength = 10),
            Country("Moldova", "MD", "373", phoneNumberLength = 8),
            Country("Monaco", "MC", "377", phoneNumberLength = 8),
            Country("Mongolia", "MN", "976", phoneNumberLength = 8),
            Country("Montenegro", "ME", "382", phoneNumberLength = 8),
            Country("Morocco", "MA", "212", phoneNumberLength = 9),
            Country("Mozambique", "MZ", "258", phoneNumberLength = 9),
            Country("Myanmar", "MM", "95", phoneNumberLength = 9),
            Country("Namibia", "NA", "264", phoneNumberLength = 9),
            Country("Nepal", "NP", "977", phoneNumberLength = 10),
            Country("Netherlands", "NL", "31", phoneNumberLength = 9),
            Country("New Zealand", "NZ", "64", phoneNumberLength = 9),
            Country("Nicaragua", "NI", "505", phoneNumberLength = 8),
            Country("Niger", "NE", "227", phoneNumberLength = 8),
            Country("Nigeria", "NG", "234", phoneNumberLength = 10),
            Country("North Korea", "KP", "850", phoneNumberLength = 10),
            Country("Norway", "NO", "47", phoneNumberLength = 8),
            Country("Oman", "OM", "968", phoneNumberLength = 8),
            Country("Pakistan", "PK", "92", phoneNumberLength = 10),
            Country("Panama", "PA", "507", phoneNumberLength = 8),
            Country("Papua New Guinea", "PG", "675", phoneNumberLength = 8),
            Country("Paraguay", "PY", "595", phoneNumberLength = 9),
            Country("Peru", "PE", "51", phoneNumberLength = 9),
            Country("Philippines", "PH", "63", phoneNumberLength = 10),
            Country("Poland", "PL", "48", phoneNumberLength = 9),
            Country("Portugal", "PT", "351", phoneNumberLength = 9),
            Country("Qatar", "QA", "974", phoneNumberLength = 8),
            Country("Romania", "RO", "40", phoneNumberLength = 9),
            Country("Russia", "RU", "7", phoneNumberLength = 10),
            Country("Rwanda", "RW", "250", phoneNumberLength = 9),
            Country("Saudi Arabia", "SA", "966", phoneNumberLength = 9),
            Country("Senegal", "SN", "221", phoneNumberLength = 9),
            Country("Serbia", "RS", "381", phoneNumberLength = 9),
            Country("Seychelles", "SC", "248", phoneNumberLength = 7),
            Country("Sierra Leone", "SL", "232", phoneNumberLength = 8),
            Country("Singapore", "SG", "65", phoneNumberLength = 8),
            Country("Slovakia", "SK", "421", phoneNumberLength = 9),
            Country("Slovenia", "SI", "386", phoneNumberLength = 8),
            Country("Somalia", "SO", "252", phoneNumberLength = 8),
            Country("South Africa", "ZA", "27", phoneNumberLength = 9),
            Country("South Korea", "KR", "82", phoneNumberLength = 10),
            Country("South Sudan", "SS", "211", phoneNumberLength = 9),
            Country("Spain", "ES", "34", phoneNumberLength = 9),
            Country("Sri Lanka", "LK", "94", phoneNumberLength = 9),
            Country("Sudan", "SD", "249", phoneNumberLength = 9),
            Country("Suriname", "SR", "597", phoneNumberLength = 7),
            Country("Sweden", "SE", "46", phoneNumberLength = 9),
            Country("Switzerland", "CH", "41", phoneNumberLength = 9),
            Country("Syria", "SY", "963", phoneNumberLength = 9),
            Country("Taiwan", "TW", "886", phoneNumberLength = 9),
            Country("Tajikistan", "TJ", "992", phoneNumberLength = 9),
            Country("Tanzania", "TZ", "255", phoneNumberLength = 9),
            Country("Thailand", "TH", "66", phoneNumberLength = 9),
            Country("Togo", "TG", "228", phoneNumberLength = 8),
            Country("Tunisia", "TN", "216", phoneNumberLength = 8),
            Country("Turkey", "TR", "90", phoneNumberLength = 10),
            Country("Turkmenistan", "TM", "993", phoneNumberLength = 8),
            Country("Uganda", "UG", "256", phoneNumberLength = 9),
            Country("Ukraine", "UA", "380", phoneNumberLength = 9),
            Country("United Arab Emirates", "AE", "971", phoneNumberLength = 9),
            Country("United Kingdom", "GB", "44", phoneNumberLength = 10),
            Country("United States", "US", "1", phoneNumberLength = 10),
            Country("Uruguay", "UY", "598", phoneNumberLength = 8),
            Country("Uzbekistan", "UZ", "998", phoneNumberLength = 9),
            Country("Venezuela", "VE", "58", phoneNumberLength = 10),
            Country("Vietnam", "VN", "84", phoneNumberLength = 9),
            Country("Yemen", "YE", "967", phoneNumberLength = 9),
            Country("Zambia", "ZM", "260", phoneNumberLength = 9),
            Country("Zimbabwe", "ZW", "263", phoneNumberLength = 9)
        )
        
        fun getAllCountries(): List<Country> = countries
        
        fun getCountryByDialCode(dialCode: String): Country? {
            return countries.find { it.dialCode == dialCode }
        }
        
        fun getCountryByCode(code: String): Country? {
            return countries.find { it.code == code }
        }
        
        fun searchCountries(query: String): List<Country> {
            val lowercaseQuery = query.lowercase()
            return countries.filter { 
                it.name.lowercase().contains(lowercaseQuery) || 
                it.dialCode.contains(lowercaseQuery) ||
                it.code.lowercase().contains(lowercaseQuery)
            }
        }
    }
}
